config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'comments/new'

  get 'comments/show'

  post 'comments/create'

  get 'comments/index'

  devise_for :users
  resources :ideas

   root 'ideas#index'

    get '/post_title_json' => 'ideas#post_title_json'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :idea

	def self.comments(params)
		return Comment.where(:post_id => params)
	end
end

app/models/idea.rb
class Idea < ActiveRecord::Base
	mount_uploader :picture, BlogPictureUploader

	def self.mounted(param)
		ideas = Idea.where(:user_id => param)
		return ideas
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  
  

  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_signin, only: [:index, :new, :show, :create]

  def new
  	@comment = Comment.new
  end

  def show
  end

  def create
  	@comment = Comment.new
    @comment.text = params[:path]
  	@comment.user_id = current_user.id
    @comment.post_id = params[:id]
  	@comment.save
  end

  def index
  end
  
  	private

  	def comment_params
      params.require(:comment).permit(:comment_text)
    end

    def check_signin
      if !user_signed_in?
        @message = "Please login before continuing."
        respond_to do |format|
          format.html { redirect_to new_user_session_path, :notice => @message }
        end
      end
    end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :check_signin, only: [:index, :new, :show, :create]

  # GET /ideas
  # GET /ideas.json
  def index
    @user = current_user
    @ideas = Idea.mounted(current_user.id).order('created_at DESC')
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @name = @idea.picture_identifier
    @user = current_user
    @comment = Comment.comments(@idea.id).order('created_at DESC')
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user_id = current_user.id
    @idea.picture = params[:picture]
    puts params[:picture].class
    
    respond_to do |format|
      if @idea.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def post_title_json
      render json: Idea.where(:name => params[:query]).map {|post| {name: post.name, value: post.id}}
  end

  private

    def check_signin
      if !user_signed_in?
        @message = "Please login before continuing."
        respond_to do |format|
          format.html { redirect_to new_user_session_path, :notice => @message }
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row content">
<div class="col-sm-2">
</div>
<div class="col-sm-8">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <p>Select a file to upload </p>
    <div class="field">
      <%= f.file_field :picture%>
    </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="/admin">Admin Panel</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, :method => :delete, :class => "btn btn-flat waves-attach waves-light waves-effect" do %>
              <span class="text-white">Logout</span></a>
              <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>



<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>Little's Blog</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="/ideas/new">New Post</a></li>
        
      </ul><br>
      <%= react_component "Search" %>
    </div>

    <div class="col-sm-9">
      <h4><small>RECENT POSTS</small></h4>
      <hr>
      <% @ideas.each do |v| %>
      <% data = v.created_at.strftime("%d %b %Y, %H:%M") %>
        <%= react_component "AllPosts", {id: v.id, date: data, name: v.name, text: v.description} %>
      <% end %>
      <br><br>
      
      
    </div>
  </div>
</div>

app/views/ideas/new.html.erb
<div class="text-center">
<h1>New Post</h1>
</div>

<%= render 'form' %>

<%= link_to 'Return', ideas_path, :class => "btn btn-flat waves-attach waves-light waves-effect" %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3">
		<%= image_tag("/uploads/#{@name}", :class => "img-responsive") %>
	</div>

	
	
	
	
	<div class="col-sm-9">
	<p>
	  <strong>Name:</strong>
	  <%= @idea.name %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @idea.description %>
	</p>
	 
	 <%= react_component "Comments", {id: @idea.id} %>

	 <% @comment.each do |c| %>
	 	<% data = c.created_at.strftime("%d %b %Y, %H:%M") %>
	 	<%= react_component "FetchComment", {comment: c, data: data} %>
	 <% end %>
	 <tr>
	 <tr>
	</div>
</div>
</div>

<div class="col-sm-5">
		<%= button_to "Delete Post", {:controller => "ideas", :action => 'destroy', :id => @idea.id}, :confirm => "Are you sure? ", :method => :delete %>
		</div>


<%= link_to 'Update', edit_idea_path(@idea), :class => "btn btn-flat waves-attach waves-light waves-effect" %> |
<%= link_to 'Go Back', ideas_path, :class => "btn btn-flat waves-attach waves-light waves-effect" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Little's Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>